sudo: false
language:  cpp
os: linux

notifications:
   slack:
     secure: "SlQwSSgHek7cVht5x5UKImUHG1W2aU0FDSlGdVUKom877JExLP1X5LOrOVnhaz95qfjHMyUjjQ9nxRrYStdwMK01Y6mSF68EZpdjctVU6XEBF3j9yOyYMQrMFJDdAsQJXowdnGw0/3oqh6Z0EzagIJXlstjKwf5bnB6CPqAbftvkKpYlbqvrKnrC8M0AZDXqYVFer++H/XwRmagHyFYYAOtEHI+ihyV3dej0YCrwcRddVN4wd1EJmE7liiQHU2Y/b6z6wARsarzgUtu7/nUEkJrP8xk817ERf2fFlpbU/QMl1HW8dpjRTx+JeUx8YPvPL7EPHMoJICZMu7LrLU3yUqfpn13ec7KbXwtDBt9uRmmELOK+LAfHFep3ODTzdNDaUtXvkJGzw7sD9/RBBIVWH+BQ4CDPd/QPzYwzlJT6vKSTYzuIHMXZ+dH/Hs2Uc2QUB3whQw0fSieFB8Sb2zL2JQwhvPbxxiOLxsSWALoaK7GPZx+uqQGIz8wb3k3sEc/SDDR0Y9IK56LS2/9AUGFAU/ykPqIf5ELQ9TDDZiNUWYL981zbCL3KcOOfSnpA59YnZwIiFHGGGIdNgI/c7yF6U/DFtLJWM7UNyIziCTjtLsFOAGTYXkmjyC/ogPXxYW0tWC8+uwToI9SpK/P/bNuiEeunC3+pGj2NcHfWMHFgON4="

compiler:
  - gcc

script: 
  - cd supla-server/Test
  - make clean && make all
  - ./supla-server
  - cd ../Release
  - make clean && make all 
